services:
  agent-builder:
    build:
      context: .
      dockerfile: Dockerfile.agent
      args:
        - KERNEL_VERSION=${KERNEL_VERSION:-5.15.0-generic}
    entrypoint: []
    command: ["echo", "Successfully built agent"]

  controller-builder:
    build:
      context: .
      dockerfile: Dockerfile.controller
    entrypoint: []
    command: ["echo", "Successfully built controller"]
