// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/controller_agent/controller_agent.proto

package controller_agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PinglistRequest_PinglistType int32

const (
	PinglistRequest_TOR_MESH  PinglistRequest_PinglistType = 0
	PinglistRequest_INTER_TOR PinglistRequest_PinglistType = 1
)

// Enum value maps for PinglistRequest_PinglistType.
var (
	PinglistRequest_PinglistType_name = map[int32]string{
		0: "TOR_MESH",
		1: "INTER_TOR",
	}
	PinglistRequest_PinglistType_value = map[string]int32{
		"TOR_MESH":  0,
		"INTER_TOR": 1,
	}
)

func (x PinglistRequest_PinglistType) Enum() *PinglistRequest_PinglistType {
	p := new(PinglistRequest_PinglistType)
	*p = x
	return p
}

func (x PinglistRequest_PinglistType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PinglistRequest_PinglistType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_controller_agent_controller_agent_proto_enumTypes[0].Descriptor()
}

func (PinglistRequest_PinglistType) Type() protoreflect.EnumType {
	return &file_proto_controller_agent_controller_agent_proto_enumTypes[0]
}

func (x PinglistRequest_PinglistType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PinglistRequest_PinglistType.Descriptor instead.
func (PinglistRequest_PinglistType) EnumDescriptor() ([]byte, []int) {
	return file_proto_controller_agent_controller_agent_proto_rawDescGZIP(), []int{3, 0}
}

// RNIC information structure
type RnicInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Qpn           uint32                 `protobuf:"varint,2,opt,name=qpn,proto3" json:"qpn,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	HostName      string                 `protobuf:"bytes,4,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	TorId         string                 `protobuf:"bytes,5,opt,name=tor_id,json=torId,proto3" json:"tor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RnicInfo) Reset() {
	*x = RnicInfo{}
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RnicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RnicInfo) ProtoMessage() {}

func (x *RnicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RnicInfo.ProtoReflect.Descriptor instead.
func (*RnicInfo) Descriptor() ([]byte, []int) {
	return file_proto_controller_agent_controller_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RnicInfo) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *RnicInfo) GetQpn() uint32 {
	if x != nil {
		return x.Qpn
	}
	return 0
}

func (x *RnicInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RnicInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *RnicInfo) GetTorId() string {
	if x != nil {
		return x.TorId
	}
	return ""
}

// Agent registration request
type AgentRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentIp       string                 `protobuf:"bytes,2,opt,name=agent_ip,json=agentIp,proto3" json:"agent_ip,omitempty"`
	Rnics         []*RnicInfo            `protobuf:"bytes,3,rep,name=rnics,proto3" json:"rnics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegistrationRequest) Reset() {
	*x = AgentRegistrationRequest{}
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistrationRequest) ProtoMessage() {}

func (x *AgentRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistrationRequest.ProtoReflect.Descriptor instead.
func (*AgentRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_agent_controller_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentRegistrationRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentRegistrationRequest) GetAgentIp() string {
	if x != nil {
		return x.AgentIp
	}
	return ""
}

func (x *AgentRegistrationRequest) GetRnics() []*RnicInfo {
	if x != nil {
		return x.Rnics
	}
	return nil
}

// Agent registration response
type AgentRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRegistrationResponse) Reset() {
	*x = AgentRegistrationResponse{}
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRegistrationResponse) ProtoMessage() {}

func (x *AgentRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRegistrationResponse.ProtoReflect.Descriptor instead.
func (*AgentRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_agent_controller_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Pinglist request
type PinglistRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	RequesterRnic *RnicInfo                    `protobuf:"bytes,1,opt,name=requester_rnic,json=requesterRnic,proto3" json:"requester_rnic,omitempty"`
	Type          PinglistRequest_PinglistType `protobuf:"varint,2,opt,name=type,proto3,enum=controller_agent.PinglistRequest_PinglistType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinglistRequest) Reset() {
	*x = PinglistRequest{}
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinglistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinglistRequest) ProtoMessage() {}

func (x *PinglistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinglistRequest.ProtoReflect.Descriptor instead.
func (*PinglistRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_agent_controller_agent_proto_rawDescGZIP(), []int{3}
}

func (x *PinglistRequest) GetRequesterRnic() *RnicInfo {
	if x != nil {
		return x.RequesterRnic
	}
	return nil
}

func (x *PinglistRequest) GetType() PinglistRequest_PinglistType {
	if x != nil {
		return x.Type
	}
	return PinglistRequest_TOR_MESH
}

// Target for ping operations
type PingTarget struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TargetRnic *RnicInfo              `protobuf:"bytes,1,opt,name=target_rnic,json=targetRnic,proto3" json:"target_rnic,omitempty"`
	// 5-tuple details
	SourcePort    uint32 `protobuf:"varint,2,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	FlowLabel     uint32 `protobuf:"varint,3,opt,name=flow_label,json=flowLabel,proto3" json:"flow_label,omitempty"`
	Priority      uint32 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingTarget) Reset() {
	*x = PingTarget{}
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingTarget) ProtoMessage() {}

func (x *PingTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingTarget.ProtoReflect.Descriptor instead.
func (*PingTarget) Descriptor() ([]byte, []int) {
	return file_proto_controller_agent_controller_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PingTarget) GetTargetRnic() *RnicInfo {
	if x != nil {
		return x.TargetRnic
	}
	return nil
}

func (x *PingTarget) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *PingTarget) GetFlowLabel() uint32 {
	if x != nil {
		return x.FlowLabel
	}
	return 0
}

func (x *PingTarget) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Pinglist response
type PinglistResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Targets         []*PingTarget          `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	ProbeIntervalMs uint32                 `protobuf:"varint,2,opt,name=probe_interval_ms,json=probeIntervalMs,proto3" json:"probe_interval_ms,omitempty"`
	TimeoutMs       uint32                 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PinglistResponse) Reset() {
	*x = PinglistResponse{}
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinglistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinglistResponse) ProtoMessage() {}

func (x *PinglistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinglistResponse.ProtoReflect.Descriptor instead.
func (*PinglistResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_agent_controller_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PinglistResponse) GetTargets() []*PingTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *PinglistResponse) GetProbeIntervalMs() uint32 {
	if x != nil {
		return x.ProbeIntervalMs
	}
	return 0
}

func (x *PinglistResponse) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// Target RNIC info request for Service Tracing
type TargetRnicInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetIp      string                 `protobuf:"bytes,1,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	TargetGid     string                 `protobuf:"bytes,2,opt,name=target_gid,json=targetGid,proto3" json:"target_gid,omitempty"` // Optional, can be used instead of IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRnicInfoRequest) Reset() {
	*x = TargetRnicInfoRequest{}
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRnicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRnicInfoRequest) ProtoMessage() {}

func (x *TargetRnicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRnicInfoRequest.ProtoReflect.Descriptor instead.
func (*TargetRnicInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_agent_controller_agent_proto_rawDescGZIP(), []int{6}
}

func (x *TargetRnicInfoRequest) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *TargetRnicInfoRequest) GetTargetGid() string {
	if x != nil {
		return x.TargetGid
	}
	return ""
}

// Target RNIC info response
type TargetRnicInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TargetRnic    *RnicInfo              `protobuf:"bytes,3,opt,name=target_rnic,json=targetRnic,proto3" json:"target_rnic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetRnicInfoResponse) Reset() {
	*x = TargetRnicInfoResponse{}
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetRnicInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetRnicInfoResponse) ProtoMessage() {}

func (x *TargetRnicInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_agent_controller_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetRnicInfoResponse.ProtoReflect.Descriptor instead.
func (*TargetRnicInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_agent_controller_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TargetRnicInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TargetRnicInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TargetRnicInfoResponse) GetTargetRnic() *RnicInfo {
	if x != nil {
		return x.TargetRnic
	}
	return nil
}

var File_proto_controller_agent_controller_agent_proto protoreflect.FileDescriptor

const file_proto_controller_agent_controller_agent_proto_rawDesc = "" +
	"\n" +
	"-proto/controller_agent/controller_agent.proto\x12\x10controller_agent\"\x81\x01\n" +
	"\bRnicInfo\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x10\n" +
	"\x03qpn\x18\x02 \x01(\rR\x03qpn\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1b\n" +
	"\thost_name\x18\x04 \x01(\tR\bhostName\x12\x15\n" +
	"\x06tor_id\x18\x05 \x01(\tR\x05torId\"\x82\x01\n" +
	"\x18AgentRegistrationRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\bagent_ip\x18\x02 \x01(\tR\aagentIp\x120\n" +
	"\x05rnics\x18\x03 \x03(\v2\x1a.controller_agent.RnicInfoR\x05rnics\"O\n" +
	"\x19AgentRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc5\x01\n" +
	"\x0fPinglistRequest\x12A\n" +
	"\x0erequester_rnic\x18\x01 \x01(\v2\x1a.controller_agent.RnicInfoR\rrequesterRnic\x12B\n" +
	"\x04type\x18\x02 \x01(\x0e2..controller_agent.PinglistRequest.PinglistTypeR\x04type\"+\n" +
	"\fPinglistType\x12\f\n" +
	"\bTOR_MESH\x10\x00\x12\r\n" +
	"\tINTER_TOR\x10\x01\"\xa5\x01\n" +
	"\n" +
	"PingTarget\x12;\n" +
	"\vtarget_rnic\x18\x01 \x01(\v2\x1a.controller_agent.RnicInfoR\n" +
	"targetRnic\x12\x1f\n" +
	"\vsource_port\x18\x02 \x01(\rR\n" +
	"sourcePort\x12\x1d\n" +
	"\n" +
	"flow_label\x18\x03 \x01(\rR\tflowLabel\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\rR\bpriority\"\x95\x01\n" +
	"\x10PinglistResponse\x126\n" +
	"\atargets\x18\x01 \x03(\v2\x1c.controller_agent.PingTargetR\atargets\x12*\n" +
	"\x11probe_interval_ms\x18\x02 \x01(\rR\x0fprobeIntervalMs\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\rR\ttimeoutMs\"S\n" +
	"\x15TargetRnicInfoRequest\x12\x1b\n" +
	"\ttarget_ip\x18\x01 \x01(\tR\btargetIp\x12\x1d\n" +
	"\n" +
	"target_gid\x18\x02 \x01(\tR\ttargetGid\"\x89\x01\n" +
	"\x16TargetRnicInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\vtarget_rnic\x18\x03 \x01(\v2\x1a.controller_agent.RnicInfoR\n" +
	"targetRnic2\xbb\x02\n" +
	"\x11ControllerService\x12h\n" +
	"\rRegisterAgent\x12*.controller_agent.AgentRegistrationRequest\x1a+.controller_agent.AgentRegistrationResponse\x12T\n" +
	"\vGetPinglist\x12!.controller_agent.PinglistRequest\x1a\".controller_agent.PinglistResponse\x12f\n" +
	"\x11GetTargetRnicInfo\x12'.controller_agent.TargetRnicInfoRequest\x1a(.controller_agent.TargetRnicInfoResponseB3Z1github.com/yuuki/rpingmesh/proto/controller_agentb\x06proto3"

var (
	file_proto_controller_agent_controller_agent_proto_rawDescOnce sync.Once
	file_proto_controller_agent_controller_agent_proto_rawDescData []byte
)

func file_proto_controller_agent_controller_agent_proto_rawDescGZIP() []byte {
	file_proto_controller_agent_controller_agent_proto_rawDescOnce.Do(func() {
		file_proto_controller_agent_controller_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_controller_agent_controller_agent_proto_rawDesc), len(file_proto_controller_agent_controller_agent_proto_rawDesc)))
	})
	return file_proto_controller_agent_controller_agent_proto_rawDescData
}

var file_proto_controller_agent_controller_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_controller_agent_controller_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_controller_agent_controller_agent_proto_goTypes = []any{
	(PinglistRequest_PinglistType)(0), // 0: controller_agent.PinglistRequest.PinglistType
	(*RnicInfo)(nil),                  // 1: controller_agent.RnicInfo
	(*AgentRegistrationRequest)(nil),  // 2: controller_agent.AgentRegistrationRequest
	(*AgentRegistrationResponse)(nil), // 3: controller_agent.AgentRegistrationResponse
	(*PinglistRequest)(nil),           // 4: controller_agent.PinglistRequest
	(*PingTarget)(nil),                // 5: controller_agent.PingTarget
	(*PinglistResponse)(nil),          // 6: controller_agent.PinglistResponse
	(*TargetRnicInfoRequest)(nil),     // 7: controller_agent.TargetRnicInfoRequest
	(*TargetRnicInfoResponse)(nil),    // 8: controller_agent.TargetRnicInfoResponse
}
var file_proto_controller_agent_controller_agent_proto_depIdxs = []int32{
	1, // 0: controller_agent.AgentRegistrationRequest.rnics:type_name -> controller_agent.RnicInfo
	1, // 1: controller_agent.PinglistRequest.requester_rnic:type_name -> controller_agent.RnicInfo
	0, // 2: controller_agent.PinglistRequest.type:type_name -> controller_agent.PinglistRequest.PinglistType
	1, // 3: controller_agent.PingTarget.target_rnic:type_name -> controller_agent.RnicInfo
	5, // 4: controller_agent.PinglistResponse.targets:type_name -> controller_agent.PingTarget
	1, // 5: controller_agent.TargetRnicInfoResponse.target_rnic:type_name -> controller_agent.RnicInfo
	2, // 6: controller_agent.ControllerService.RegisterAgent:input_type -> controller_agent.AgentRegistrationRequest
	4, // 7: controller_agent.ControllerService.GetPinglist:input_type -> controller_agent.PinglistRequest
	7, // 8: controller_agent.ControllerService.GetTargetRnicInfo:input_type -> controller_agent.TargetRnicInfoRequest
	3, // 9: controller_agent.ControllerService.RegisterAgent:output_type -> controller_agent.AgentRegistrationResponse
	6, // 10: controller_agent.ControllerService.GetPinglist:output_type -> controller_agent.PinglistResponse
	8, // 11: controller_agent.ControllerService.GetTargetRnicInfo:output_type -> controller_agent.TargetRnicInfoResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_controller_agent_controller_agent_proto_init() }
func file_proto_controller_agent_controller_agent_proto_init() {
	if File_proto_controller_agent_controller_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_controller_agent_controller_agent_proto_rawDesc), len(file_proto_controller_agent_controller_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_controller_agent_controller_agent_proto_goTypes,
		DependencyIndexes: file_proto_controller_agent_controller_agent_proto_depIdxs,
		EnumInfos:         file_proto_controller_agent_controller_agent_proto_enumTypes,
		MessageInfos:      file_proto_controller_agent_controller_agent_proto_msgTypes,
	}.Build()
	File_proto_controller_agent_controller_agent_proto = out.File
	file_proto_controller_agent_controller_agent_proto_goTypes = nil
	file_proto_controller_agent_controller_agent_proto_depIdxs = nil
}
