// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/controller_agent/controller_agent.proto

package controller_agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControllerService_RegisterAgent_FullMethodName     = "/controller_agent.ControllerService/RegisterAgent"
	ControllerService_GetPinglist_FullMethodName       = "/controller_agent.ControllerService/GetPinglist"
	ControllerService_GetTargetRnicInfo_FullMethodName = "/controller_agent.ControllerService/GetTargetRnicInfo"
)

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Controller service definition
type ControllerServiceClient interface {
	// Register an agent and its RNICs
	RegisterAgent(ctx context.Context, in *AgentRegistrationRequest, opts ...grpc.CallOption) (*AgentRegistrationResponse, error)
	// Get pinglist for an agent
	GetPinglist(ctx context.Context, in *PinglistRequest, opts ...grpc.CallOption) (*PinglistResponse, error)
	// Get target RNIC info for service tracing
	GetTargetRnicInfo(ctx context.Context, in *TargetRnicInfoRequest, opts ...grpc.CallOption) (*TargetRnicInfoResponse, error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) RegisterAgent(ctx context.Context, in *AgentRegistrationRequest, opts ...grpc.CallOption) (*AgentRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRegistrationResponse)
	err := c.cc.Invoke(ctx, ControllerService_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetPinglist(ctx context.Context, in *PinglistRequest, opts ...grpc.CallOption) (*PinglistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PinglistResponse)
	err := c.cc.Invoke(ctx, ControllerService_GetPinglist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetTargetRnicInfo(ctx context.Context, in *TargetRnicInfoRequest, opts ...grpc.CallOption) (*TargetRnicInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetRnicInfoResponse)
	err := c.cc.Invoke(ctx, ControllerService_GetTargetRnicInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility.
//
// Controller service definition
type ControllerServiceServer interface {
	// Register an agent and its RNICs
	RegisterAgent(context.Context, *AgentRegistrationRequest) (*AgentRegistrationResponse, error)
	// Get pinglist for an agent
	GetPinglist(context.Context, *PinglistRequest) (*PinglistResponse, error)
	// Get target RNIC info for service tracing
	GetTargetRnicInfo(context.Context, *TargetRnicInfoRequest) (*TargetRnicInfoResponse, error)
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServiceServer struct{}

func (UnimplementedControllerServiceServer) RegisterAgent(context.Context, *AgentRegistrationRequest) (*AgentRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedControllerServiceServer) GetPinglist(context.Context, *PinglistRequest) (*PinglistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPinglist not implemented")
}
func (UnimplementedControllerServiceServer) GetTargetRnicInfo(context.Context, *TargetRnicInfoRequest) (*TargetRnicInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTargetRnicInfo not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}
func (UnimplementedControllerServiceServer) testEmbeddedByValue()                           {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s grpc.ServiceRegistrar, srv ControllerServiceServer) {
	// If the following call pancis, it indicates UnimplementedControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerService_ServiceDesc, srv)
}

func _ControllerService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).RegisterAgent(ctx, req.(*AgentRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetPinglist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinglistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetPinglist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetPinglist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetPinglist(ctx, req.(*PinglistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetTargetRnicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetRnicInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetTargetRnicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetTargetRnicInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetTargetRnicInfo(ctx, req.(*TargetRnicInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerService_ServiceDesc is the grpc.ServiceDesc for ControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controller_agent.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _ControllerService_RegisterAgent_Handler,
		},
		{
			MethodName: "GetPinglist",
			Handler:    _ControllerService_GetPinglist_Handler,
		},
		{
			MethodName: "GetTargetRnicInfo",
			Handler:    _ControllerService_GetTargetRnicInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/controller_agent/controller_agent.proto",
}
