apiVersion: 1
datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: "10s"     # matches the agent periodic reader flush interval
    editable: false
