name: Go Tests

on:
  push:
  pull_request:

# Prevent concurrent runs of the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  controller-test:
    name: Controller integration tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Compose
      uses: docker/setup-buildx-action@v3

    - name: Run tests
      run: make test
